b = [
 [['Breakfast',
   '-- Main Entree --',
   'Breakfast Sausage Patties',
   'Make Your Own Breakfast Fajita',
   "O'Brien Potatoes",
   'Scrambled Eggs',
   '-- Entrees --',
   'European Style Breakfast Station',
   '-- Grill --',
   'A la minute omelet station with fresh ingredients',
   'Eggs Made to Order',
   'French Toast or Pancakes',
   '-- Breakfast Bars --',
   'Oatmeal Bar',
   'Pancake & Waffle Toppings',
   '-- Breads --',
   'Bagels',
   'House Prepared Cinnamon Bread',
   'Whole Grain Roll',
   '-- Specialty Bars --',
   'Make Your Own Yogurt Parfait Station'],
  ['Breakfast',
   '-- Main Entree --',
   'Eggs Made to Order',
   'Grits',
   'Oatmeal',
   'Pancakes',
   '-- On the Side --',
   'Home Fried Potatoes',
   '-- Specialty Bars --',
   'Sliced Bagels',
   'Yogurt Bar',
   '-- Desserts --',
   'Assorted Danish',
   'Assorted Muffins'],
  ['Breakfast',
   '-- Entrees --',
   'Assorted Breakfast Meats',
   'Assorted Hot Breakfast Cereal',
   'Gallo Pinto - Rice & Beans',
   'Scrambled Eggs',
   '-- Cereals --',
   'Oatmeal Bar',
   '-- Grill --',
   'Assorted Pancakes',
   'Breakfast Potatoes',
   'Egg, Tomato & Pesto Quesadilla',
   'Ham, Egg & Cheese on English Muffin',
   'Omelet Bar with Pork Options',
   '-- Breakfast Bars --',
   'Sweet & Savory Yogurt Bar'],
  ['Breakfast',
   '-- Main Entree --',
   'Eggs Made to Order',
   'French Texas Toast',
   'Omelet Bar with Pork Options',
   'Scrambled Eggs',
   '-- Starches --',
   'Country Hash Browns',
   '-- Sandwiches --',
   'Bacon, Egg & Cheese on English Muffin',
   'Egg & Cheese on a English Muffin',
   '-- Specialty Bars --',
   'Congee',
   'Scrambled Tofu',
   'Vegan Fruit Smoothies',
   '-- From our Bakeshop --',
   'Fresh Baked Muffin'],
  ['Breakfast',
   '-- Entrees --',
   'Buttermilk Pancakes',
   'Eggs Any Style & Omelets Made to Order',
   'Pork Sausage Links',
   'Scrambled Eggs',
   'Tater Tots',
   'Vegan Tofu Scramble',
   '-- Breakfast Bars --',
   'Assorted Bagels & Bakery Fresh Donuts',
   'Make Your Own Fajita',
   'Seasonal Roasted Vegetable Platter',
   'Vegan Chia Seed Pudding',
   'Yogurt & Fruit Mix-ins'],
  []],
 [['Breakfast',
   '-- Main Entree --',
   'Breakfast Sausage Patties',
   'Make Your Own Breakfast Fajita',
   "O'Brien Potatoes",
   'Scrambled Eggs',
   '-- Entrees --',
   'European Style Breakfast Station',
   '-- Grill --',
   'A la minute omelet station with fresh ingredients',
   'Eggs Made to Order',
   'French Toast or Pancakes',
   '-- Breakfast Bars --',
   'Oatmeal Bar',
   'Pancake & Waffle Toppings',
   '-- Breads --',
   'Bagels',
   'House Prepared Cinnamon Bread',
   'Whole Grain Roll',
   '-- Specialty Bars --',
   'Make Your Own Yogurt Parfait Station'],
  ['Breakfast',
   '-- Main Entree --',
   'Grits',
   'Oatmeal',
   'Scrambled Eggs',
   'Waffles',
   '-- On the Side --',
   'Home Fried Potatoes',
   '-- Specialty Bars --',
   'Sliced Bagels',
   '-- Desserts --',
   'Assorted Danish',
   'Assorted Muffins'],
  ['Breakfast',
   '-- Entrees --',
   'Assorted Breakfast Meats',
   'Assorted Hot Breakfast Cereal',
   'Scrambled Egg Bar with Ham',
   '-- Cereals --',
   'Oatmeal Bar',
   '-- Grill --',
   'Breakfast Potatoes',
   'Egg, Tomato & Pesto Quesadilla',
   'French Texas Toast',
   'Omelet Bar with Pork Options'],
  ['Breakfast',
   '-- Main Entree --',
   'Eggs Made to Order',
   'French Texas Toast',
   'Omelet Bar with Pork Options',
   'Scrambled Eggs',
   '-- Starches --',
   'Hash Browns',
   '-- Sandwiches --',
   'Bacon, Egg & Cheese on English Muffin',
   'Egg & Cheese on a English Muffin',
   '-- Specialty Bars --',
   'Miso Soup & Organic Tofu',
   'Scrambled Tofu',
   'Steamed White Rice',
   '-- From our Bakeshop --',
   'Fresh Baked Muffin'],
  ['Breakfast',
   '-- Entrees --',
   'Eggs Any Style & Omelets Made to Order',
   'French Texas Toast',
   'Grilled Turkey Sausage Patty',
   'Home Fried Potatoes',
   'Scrambled Eggs',
   'Vegan Tofu Scramble',
   '-- Breakfast Bars --',
   'Assorted Bagels & Bakery Fresh Donuts',
   'Frozen Fruit & Yogurt Smoothie',
   'Make Your Own Fajita',
   'Seasonal Roasted Vegetable Platter',
   'Yogurt & Fruit Mix-ins'],
  []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []]]

l = [
 [['Lunch',
   '-- Main Entree --',
   'Old Fashioned Beef Stew',
   '-- Soup of the Day --',
   'Manhattan Clam Chowder',
   'Moroccan Lentil Soup',
   '-- Vegan Salads --',
   'Fresh vegetables, fruit, sprouts, seeds, legumes & greens',
   'Up to ten daily varieties of freshly composed salads',
   '-- On the Side --',
   'Buttermilk Biscuit',
   'Mashed Red Bliss Potatoes',
   'Sautéed Broccoli',
   '-- Action Station --',
   'Beans, Greens & Grains, A la Minute Saute Station',
   '-- From our Bakeshop --',
   'Black Bean Brownie'],
  ['Lunch',
   '-- Vegetarian & Vegan Entree --',
   'Red Quinoa & Black Beans',
   '-- Soups --',
   'Cream of Mushroom Soup',
   '-- Salads --',
   'Salad Bar',
   '-- Fruit --',
   'Fresh Fruit Salad',
   '-- On the Side --',
   'Refried Beans',
   'Vegan Spanish Rice',
   'Vegetable of the Day',
   '-- Specialty Bars --',
   'Pasta Bar',
   'Taco Bar'],
  ['Lunch',
   '-- Euro Entree --',
   'Southwest Beef Lasagna',
   '-- Vegetarian & Vegan Entree --',
   'Vegetarian Southwest Lasagna',
   '-- Soups --',
   'Black Bean Soup',
   'New England Clam Chowder',
   '-- Salads --',
   'Freshly Made Grain, Hummus & Composed Salads',
   '-- Grill Special --',
   'Greek Turkey Burger',
   '-- On the Side --',
   'Pasta',
   'Twice Baked Potatoes',
   'Vegetable of the Day',
   '-- From our Bakeshop --',
   'Black Bean Brownie'],
  ['Lunch',
   '-- Main Entree --',
   'Daikon Radish & Carrots',
   'Dim Sum Bar',
   'Vietnamese Pork',
   '-- Soup of the Day --',
   'Cuban Style Black Bean Soup',
   'New England Clam Chowder',
   '-- Salads --',
   'Mediterranean Spinach Salad',
   '-- Pasta Station --',
   'Orecchiette with Asparagus & Roasted Peppers',
   '-- Grill Special --',
   'Seafood & Grain Burger',
   '-- Action Station --',
   'Black Bean & Corn Salsa',
   'Greek Salsa',
   'Pico de Gallo',
   'Sweet & Sour Asian Cheese Vegadilla',
   '-- From our Bakeshop --',
   'Black Bean Brownie'],
  ['Lunch',
   '-- Main Entree --',
   'Philly Chicken Steak Sandwich Wrap',
   '-- Entree Salads --',
   'Pineapple Salad with Jicama & Avocado',
   'Southwest Chicken Salad',
   '-- Vegetarian & Vegan Entree --',
   'Black Beans, Corn & Rice',
   '-- Soups --',
   'Tomato Soup',
   '-- Salads --',
   'Egg Salad',
   'Salad Bar Mixed Salads',
   '-- Breakfast Bars --',
   'Eggs Any Style & Omelets Made to Order',
   'Yogurt & Fruit Mix-ins',
   '-- Pasta Station --',
   'Pasta Selection of The Day',
   '-- On the Side --',
   'Fresh Cauliflower',
   '-- Specialty Bars --',
   'Forbes Deli',
   '-- From our Bakeshop --',
   'Black Bean Brownie'],
  []],
 [['Lunch',
   '-- Main Entree --',
   'Baja Fish Taco',
   '-- Vegetarian & Vegan Entree --',
   'Chayote Guisado',
   'Latin Black Beans and Rice',
   '-- Soup of the Day --',
   'Chicken Orzo Soup',
   'Vegetable Barley Soup',
   '-- Vegan Salads --',
   'Fresh vegetables, fruit, sprouts, seeds, legumes & greens',
   'Up to ten daily varieties of freshly composed salads',
   '-- On the Side --',
   'Baja Sauce',
   'Firey Salsa',
   'Salsa Verde',
   '-- Action Station --',
   'Beans, Greens & Grains, A la Minute Saute Station',
   '-- From our Bakeshop --',
   'Chocolate Fudge Cake'],
  ['Lunch',
   '-- Main Entree --',
   'Chicken Tenders',
   '-- Soups --',
   'Mushroom Barley Soup',
   '-- Salads --',
   'Salad Bar',
   '-- Fruit --',
   'Fresh Fruit Salad',
   '-- On the Side --',
   'Spicy French Fries',
   'Vegetable of the Day',
   '-- Specialty Bars --',
   'Deli Bar',
   'Pasta Bar'],
  ['Lunch',
   '-- Euro Entree --',
   'Simple Beef Stew',
   '-- Vegetarian & Vegan Entree --',
   'Vegetable Stew',
   '-- Soups --',
   'Chicken Posole',
   'Southwest Tortilla Soup',
   '-- Salads --',
   'Freshly Made Grain, Hummus & Composed Salads',
   "-- Chef's Special --",
   'Cheese Ravioli',
   '-- On the Side --',
   'Pasta',
   'Vegetable of the Day',
   'White Rice',
   '-- From our Bakeshop --',
   'Chocolate Fudge Cake'],
  ['Lunch',
   '-- Main Entree --',
   'Meatballs in Tomato Sauce',
   '-- Vegetarian & Vegan Entree --',
   'Eggplant Rollatini',
   '-- Soup of the Day --',
   'New England Clam Chowder',
   'Tomato Bisque',
   '-- Salads --',
   'Tossed House Salad',
   '-- Pasta Station --',
   'Pasta with Clam Sauce',
   '-- Grill Special --',
   'Seafood & Grain Burger',
   '-- On the Side --',
   'Fettucine Alfredo',
   'Sautéed Spinach',
   '-- Action Station --',
   'Avocado Queso & Hummus Vegadilla',
   'Black Bean & Corn Salsa',
   'Greek Salsa',
   'Pico de Gallo',
   '-- From our Bakeshop --',
   'Chocolate Fudge Cake'],
  ['Lunch',
   '-- Entree Salads --',
   'Cubano Salad',
   'Vegetable Ranch Salad',
   '-- Vegetarian & Vegan Entree --',
   'Ancient Grain Bowl',
   '-- Soups --',
   'Vegetable Barley Soup',
   '-- Salads --',
   'Cole Slaw',
   'Salad Bar Mixed Salads',
   '-- Breakfast Bars --',
   'Eggs Any Style & Omelets Made to Order',
   'Yogurt & Fruit Mix-ins',
   '-- Pasta Station --',
   'Pasta Selection of the Day',
   '-- Sandwiches --',
   'Reuban Panini',
   '-- On the Side --',
   'Julienne Vegetable Medley',
   '-- Specialty Bars --',
   'Forbes Deli',
   '-- From our Bakeshop --',
   'Chocolate Fudge Cake'],
  []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []]]

d = [
 [['Dinner',
   '-- Main Entree --',
   'Baked Cheese Ziti',
   'Buffalo Wings',
   'Caribbean Wings',
   'Korean Chicken Wings',
   'Lemon Pepper Wings',
   '-- Soup of the Day --',
   'Manhattan Clam Chowder',
   'Moroccan Lentil Soup',
   '-- Vegan Salads --',
   'Fresh vegetables, fruit, sprouts, seeds, legumes & greens',
   'Up to ten daily varieties of freshly composed salads',
   '-- On the Side --',
   'Black Beans & Corn',
   '-- Action Station --',
   'Beans, Greens & Grains, A la Minute Saute Station',
   '-- Specialty Bars --',
   'Immune Booster Smoothie',
   'Wilson Smoothie',
   '-- From our Bakeshop --',
   'Butterbeer Cupcakes',
   'Dutch Apple Crumb Cake'],
  ['Dinner',
   '-- Main Entree --',
   'Acadian Red Fish a la meuniere',
   'Hot Remoulade Sauce',
   '-- Soups --',
   'Cream of Mushroom Soup',
   '-- Salads --',
   'Salad Bar',
   '-- Fruit --',
   'Fresh Fruit Salad',
   '-- On the Side --',
   'Black Rice Risotto',
   'Vegetable of the Day',
   '-- Specialty Bars --',
   'Baked Potato Bar',
   'Pasta Bar',
   'Potato Bar Accompaniments',
   '-- Desserts --',
   'Chocolate Chip Cookies',
   'Double Chocolate Cake',
   'Oatmeal Cookies'],
  ['Dinner',
   '-- Euro Entree --',
   'BBQ Chicken',
   'Pulled Pork',
   '-- Vegetarian & Vegan Entree --',
   'Carrot & Lentil Stew',
   '-- Soups --',
   'Black Bean Soup',
   'New England Clam Chowder',
   '-- Salads --',
   'Freshly Made Grain, Hummus & Composed Salads',
   '-- Grill Special --',
   'Greek Turkey Burger',
   '-- On the Side --',
   'Macaroni & Cheese',
   'Pasta',
   'Vegetable of the Day',
   '-- From our Bakeshop --',
   'Butterbeer Cupcakes',
   'Dutch Apple Crumb Cake'],
  ['Dinner',
   '-- Main Entree --',
   'Braised Beef Short Ribs',
   '-- Vegetarian & Vegan Entree --',
   'Quinoa & Black Beans',
   '-- Soup of the Day --',
   'Cuban Style Black Bean Soup',
   'New England Clam Chowder',
   '-- Salads --',
   'Mediterranean Spinach Salad',
   '-- Pasta Station --',
   'Orecchiette with Asparagus & Roasted Peppers',
   '-- Grill Special --',
   'Seafood & Grain Burger',
   '-- On the Side --',
   'Cheese & Onion Mashed Potatoes',
   'Roasted Root Vegetables',
   '-- Action Station --',
   'Onion Ring & Twister Fries Bar',
   '-- From our Bakeshop --',
   'Butterbeer Cupcakes',
   'Dutch Apple Crumb Cake'],
  ['Dinner',
   '-- Main Entree --',
   'Shredded Beef with Nachos & Salsa Verde',
   '-- Vegetarian & Vegan Entree --',
   'Vegetable Quinoa Saute',
   '-- Salads --',
   'Salad Bar Mixed Salads',
   '-- On the Side --',
   'Corn',
   '-- Specialty Bars --',
   'Guacamole',
   'Salsas & Hand Made Corn Tortilla Chips',
   '-- From our Bakeshop --',
   'Butterbeer Cupcakes',
   'Dutch Apple Crumb Cake'],
  ['Dinner',
   '-- Main Entree --',
   'Chicken Parmesan',
   'Penne with Pork Bolognese',
   '-- Vegetarian & Vegan Entree --',
   'Stuffed Red Bell Peppers with Kale & Rice',
   '-- Soups --',
   'Cream of Roasted Tomato Soup',
   'White Bean Sausage & Ham Soup',
   '-- On the Side --',
   'Braised Swiss Chard',
   'Italian Green Beans & Red Pepper',
   'Roasted Yukon Gold Potatoes',
   '-- From our Bakeshop --',
   'Black Bean Brownie',
   'Butterbeer Cupcakes',
   'Dutch Apple Crumb Cake']],
 [['Dinner',
   '-- Main Entree --',
   'Beef with Broccoli',
   'Shrimp with Broccoli',
   '-- Vegetarian & Vegan Entree --',
   'Vegetable Fried Rice',
   '-- Soup of the Day --',
   'Chicken Orzo Soup',
   'Lentil Soup',
   '-- Vegan Salads --',
   'Fresh vegetables, fruit, sprouts, seeds, legumes & greens',
   'Up to ten daily varieties of freshly composed salads',
   '-- On the Side --',
   'Egg Rolls',
   'Fresh Green Beans',
   'Roasted Butternut Squash',
   '-- Action Station --',
   'Beans, Greens & Grains, A la Minute Saute Station',
   '-- Specialty Bars --',
   'Pina Colada Smoothie',
   'Tiger Smoothie',
   '-- From our Bakeshop --',
   'Orange Sugar Cookie',
   'Vegan Blackberry Peach Bar'],
  ['Dinner',
   '-- Main Entree --',
   'Braised Beef Short Ribs',
   'Roast Turkey',
   '-- Vegetarian & Vegan Entree --',
   'Mustard Crusted Tofu with Braised Kale',
   '-- Soups --',
   'Vegetable Matzoh Ball Soup',
   '-- Salads --',
   'Salad Bar',
   '-- Fruit --',
   'Fresh Fruit Salad',
   '-- On the Side --',
   'Challah Bread',
   'Herb Oil',
   'Vegan Bread Stuffing',
   'Vegetable Quinoa Paella',
   'Vegetable of the Day',
   '-- Desserts --',
   'Chocolate Chip Cookies',
   'Honey Cake',
   'Oatmeal Cookies'],
  ['Dinner',
   '-- Euro Entree --',
   'Basil Chicken & Roast Peppers',
   'Fish of the Day',
   '-- Vegetarian & Vegan Entree --',
   'Cannellini Beans with Spinach',
   '-- Soups --',
   'Chicken Posole',
   'Southwest Tortilla Soup',
   '-- Salads --',
   'Freshly Made Grain, Hummus & Composed Salads',
   '-- On the Side --',
   'Pasta',
   'Ruby Wild Rice Blend',
   'Vegetable of the Day',
   '-- From our Bakeshop --',
   'Orange Sugar Cookie',
   'Vegan Blackberry Peach Bar'],
  ['Dinner',
   '-- Main Entree --',
   'Mongolian Seafood with Vegetables',
   '-- Vegetarian & Vegan Entree --',
   'Vegetable Fried Rice & Tofu',
   '-- Soup of the Day --',
   'New England Clam Chowder',
   'Tomato Bisque',
   '-- Salads --',
   'Tossed House Salad',
   '-- Pasta Station --',
   'Pasta with Clam Sauce',
   '-- Grill Special --',
   'Seafood & Grain Burger',
   '-- On the Side --',
   'Lemongrass Water',
   'Mongolian Sauce',
   'Mongolian Tofu & Veg Stirfry',
   '-- From our Bakeshop --',
   'Orange Sugar Cookie',
   'Vegan Blackberry Peach Bar'],
  ['Dinner',
   '-- Main Entree --',
   'Char Grilled Ginger Soy Beef',
   'Ginger Soy Chicken',
   'Vegan Tofu Scramble',
   '-- Salads --',
   'Salad Bar Mixed Salads',
   '-- On the Side --',
   'Steamed Jasmine Rice',
   '-- From our Bakeshop --',
   'Orange Sugar Cookie',
   'Vegan Blackberry Peach Bar'],
  ['Dinner',
   '-- Main Entree --',
   'BBQ Chicken',
   'Fried Catch of the Day',
   '-- Vegetarian & Vegan Entree --',
   'Baked Macaroni & Cheese',
   '-- Soups --',
   'Chicken & Andouille Sausage Corn Chowder',
   'Mushroom Barley Soup',
   '-- On the Side --',
   'Brazilian Vegetables',
   'Fresh Sauteed Mixed Vegetables',
   'Vegan Dirty Rice',
   '-- From our Bakeshop --',
   'Chocolate Fudge Cake',
   'Orange Sugar Cookie',
   'Vegan Blackberry Peach Bar']],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []],
 [[], [], [], [], [], []]]